[tool.ruff]
line-length = 120

[tool.ruff.lint]
# Enable flake8-bugbear (`B`) rules.
select = [
    "E", "F", "B", "PL", "S", "W", "N", "G", "C4", "EM",
    "ISC", "ICN", "PIE", "T20", "PYI", "PT", "RET", "INT", "RUF"
]
ignore = [
    "S101",  # `zip()` without an explicit `strict=` parameter
]

# Ignore `E501` (line length) in all `__init__.py`  and migration files
[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["E501"]
